name: CI

on:
  push:
    branches:
      - "**"

jobs:

  php83:
    name: "php 8.3"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.3"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E,4AA394086372C20A

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Chesk code style
        run: tools/php-cs-fixer fix --dry-run --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --memory-limit=-1

      - name: Run tests
        run: tools/phpunit test/ --bootstrap vendor/autoload.php

  php82:
    name: "php 8.2"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.2"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E,4AA394086372C20A

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --memory-limit=-1

      - name: Run tests
        run: tools/phpunit test/ --bootstrap vendor/autoload.php

  php82a:
    name: "php 8.2, laravel 9, PSR log 2, symfony 6"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.2"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E,4AA394086372C20A

      - name: Install dependencies
        run: composer update --no-interaction --with illuminate/support:^9.0 --with psr/log:^2.0 --with symfony/http-foundation:^6.0 --with symfony/http-kernel:^6.0 --with symfony/psr-http-message-bridge:^6.0

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --memory-limit=-1

      - name: Run tests
        run: tools/phpunit test/ --bootstrap vendor/autoload.php

  php81:
    name: "php 8.1"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --memory-limit=-1

      - name: Run tests
        run: vendor/bin/phpunit test/

  php81a:
    name: "php 8.1, laravel 8, symfony 5, PSR bridge 2"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --with illuminate/support:^8.81 --with symfony/http-kernel:^5.4 --with symfony/http-foundation:^5.4 --with symfony/psr-http-message-bridge:^2.1

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --memory-limit=-1

      - name: Run tests
        run: vendor/bin/phpunit test/
