name: CI

on:
  push:
    branches:
      - "*"

jobs:

  php81:
    name: "php 8.1"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Chesk code style
        run: vendor/bin/php-cs-fixer fix --dry-run --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/

  php81a:
    name: "php 8.1, laravel 8, symfony 5, validator 0.3"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --with illuminate/support:^8.81 --with symfony/http-kernel:^5.4 --with symfony/http-foundation:^5.4 --with simple-as-fuck/php-validator:^0.3.0

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/

  php80:
    name: "php 8.0"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.0"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/

  php74:
    name: "php 7.4"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:7.4"
    services:
      database:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/
